#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="SRFPisoCentralFoam"

runApplication blockMesh
transformPoints -translate "(0 0.19285 0)" 
runApplication $application
