#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="SRFPisoCentralFoam"

#GGI-related stuff
#runApplication setSet -batch setBatch
#runApplication regionCellSets
#runApplication setsToZones -noFlipMap

runApplication $application
